### ISSUE TITLE
Find ApproxCholLap function didn't finish in one example

### ISSUE THREAD

**Issue by qlyu2016** [danspielman/Laplacians.jl#10]
Hi,

Here is the thing I noticed: when I tried to use approxCholLap function to deal with one graph, it didn't finish within a reasonable time. However, cholLap function went on well with the same graph. Therefore, I just want to report this unsuccessful case.
Here is the code that didn't work:
https://github.com/qlyu2016/Homework/tree/master/EffectiveResistancesJulia
main.jl is the main entry for testing. 
ca-GrQc stores the data file.

Thanks,
Qian Lyu

**Comment by danspielman** [comment]
You are correct.  This is definitely a bug.
Thanks for finding it!
I will look into it.

**Comment by danspielman** [comment]
The issue was that this matrix had a nonzero diagonal.
I have adjusted the function approxCholLap so that it now issues a warning
if the input matrix has a nonzero diagonal, and then strips it out.
The purpose of the warning is to advise that there will be some performance loss.

This fix is now in the master version.  Will put it into a release soon.

**Comment by qlyu2016** [comment]
Thanks very much!
